trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  bkstrgrg: 'rg-sanhorva'
  bkstrg: 'sasanhorva'
  bkcontainer: 'tfstate-shsz-03'
  #prefix: 'shsz'
  #bkstrgkey: 'terraform.tfstate'
  IMAGE_REPO: interiordesign/apim
  TAG: '$(Build.BuildId)'

stages:
# build the docker image and push it to dockerhub
  - stage: Build
    displayName: Build&Push
    jobs:
      - job: build_and_push
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'dockerhub'
            repository: '$(IMAGE_REPO)'
            command: 'buildAndPush'
            Dockerfile: '$(Build.SourcesDirectory)/app/Dockerfile'

        # Publish the manifests as artifacts
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(Pipeline.Workspace)/s/app'
            artifact: 'manifests'
            publishLocation: 'pipeline'